# Generated by Django 4.1.4 on 2023-01-02 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0002_secretario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario_de_inicio_lunes', models.TimeField()),
                ('horario_de_fin_lunes', models.TimeField()),
                ('horario_de_inicio_segundo_turno_lunes', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_lunes', models.TimeField(blank=True)),
                ('horario_de_inicio_martes', models.TimeField()),
                ('horario_de_fin_martes', models.TimeField()),
                ('horario_de_inicio_segundo_turno_martes', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_martes', models.TimeField(blank=True)),
                ('horario_de_inicio_miercoles', models.TimeField()),
                ('horario_de_fin_miercoles', models.TimeField()),
                ('horario_de_inicio_segundo_turno_miercoles', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_miercoles', models.TimeField(blank=True)),
                ('horario_de_inicio_jueves', models.TimeField()),
                ('horario_de_fin_jueves', models.TimeField()),
                ('horario_de_inicio_segundo_turno_jueves', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_jueves', models.TimeField(blank=True)),
                ('horario_de_inicio_viernes', models.TimeField()),
                ('horario_de_fin_viernes', models.TimeField()),
                ('horario_de_inicio_segundo_turno_viernes', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_viernes', models.TimeField(blank=True)),
                ('horario_de_inicio_sabado', models.TimeField()),
                ('horario_de_fin_sabado', models.TimeField()),
                ('horario_de_inicio_segundo_turno_sabado', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_sabado', models.TimeField(blank=True)),
                ('horario_de_inicio_domingo', models.TimeField()),
                ('horario_de_fin_domingo', models.TimeField()),
                ('horario_de_inicio_segundo_turno_domingo', models.TimeField(blank=True)),
                ('horario_de_fin_segundo_turno_domingo', models.TimeField(blank=True)),
                ('id_de_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
