# Generated by Django 4.1.4 on 2023-01-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0005_alter_horario_horario_de_fin_segundo_turno_domingo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chofer',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='chofer',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
