# Generated by Django 4.1.4 on 2023-01-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0006_alter_chofer_direccion_alter_chofer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_oficina', models.CharField(max_length=255)),
                ('direccion', models.TextField()),
                ('chofer', models.ManyToManyField(blank=True, default=0, related_name='choferes_que_trabajan_en_oficina', to='app_horarios.chofer')),
            ],
        ),
        migrations.AddField(
            model_name='horario',
            name='oficina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_este_horario', to='app_horarios.oficina'),
        ),
    ]
