# Generated by Django 4.1.4 on 2023-01-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0007_oficina_horario_oficina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficina',
            name='chofer',
            field=models.ManyToManyField(blank=True, default=[0], related_name='choferes_que_trabajan_en_oficina', to='app_horarios.chofer'),
        ),
    ]
