# Generated by Django 4.1.4 on 2023-01-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0008_alter_oficina_chofer'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='nombre_del_horario',
            field=models.CharField(default='', max_length=255),
        ),
    ]
