# Generated by Django 4.1.4 on 2023-01-03 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0010_alter_horario_horario_de_fin_domingo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='id_de_usuario',
        ),
        migrations.AddField(
            model_name='horario',
            name='id_de_chofer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer', to='app_horarios.chofer'),
        ),
    ]
