# Generated by Django 4.1.4 on 2023-01-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0011_remove_horario_id_de_usuario_horario_id_de_chofer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_reporte_de_asistencia', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='secretario',
            name='el_usuario_es_secretario',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], max_length=2),
        ),
    ]
