# Generated by Django 4.1.4 on 2023-01-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0012_asistencia_alter_secretario_el_usuario_es_secretario'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_de_chofer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_para_asistencia', to='app_horarios.chofer'),
        ),
    ]
