# Generated by Django 4.1.4 on 2023-01-03 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0015_alter_asistencia_fecha_y_hora_en_la_que_se_registro_asistencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_reporte_semanal', models.CharField(default='', max_length=255)),
                ('fecha_de_inicio_de_semana_a_evaluar', models.DateField(default=datetime.date.today)),
                ('fecha_final_de_semana_a_evaluar', models.DateField(default=datetime.date.today)),
                ('clases_cambiadas_a_otro_horario', models.TextField(blank=True, null=True)),
                ('horas_trabajadas_en_la_semana', models.IntegerField(default=0)),
                ('clases_canceladas_en_la_semana', models.IntegerField(default=0)),
                ('motivo_de_las_inasistencias', models.TextField(blank=True, null=True)),
                ('fecha_y_hora_en_la_que_se_registro_reporte', models.DateTimeField(auto_now_add=True)),
                ('id_de_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_chofer_para_reporte_semanal', to='app_horarios.chofer')),
            ],
        ),
    ]
