# Generated by Django 4.1.4 on 2023-01-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0016_reportesemanal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('usara_carro_automatico_o_sincronico', models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='chofer',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
