# Generated by Django 4.1.4 on 2023-01-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0017_estudiante_alter_chofer_dni_delete_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usara_carro_automatico_o_sincronico',
        ),
    ]
