# Generated by Django 4.1.4 on 2023-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0018_remove_estudiante_usara_carro_automatico_o_sincronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='secretario',
            name='esta_dentro_del_horario_de_trabajo',
            field=models.BooleanField(default=True),
        ),
    ]
