# Generated by Django 4.1.4 on 2023-01-07 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0019_secretario_esta_dentro_del_horario_de_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosLunes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_este_horario', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer', to='app_horarios.estudiante')),
            ],
        ),
    ]
