# Generated by Django 4.1.4 on 2023-01-07 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0020_horarioslunes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioslunes',
            name='id_de_oficina',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_lunes', to='app_horarios.oficina'),
        ),
        migrations.AlterField(
            model_name='horarioslunes',
            name='id_del_chofer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_lunes', to='app_horarios.chofer'),
        ),
        migrations.AlterField(
            model_name='horarioslunes',
            name='id_del_estudiante',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_lunes', to='app_horarios.estudiante'),
        ),
        migrations.CreateModel(
            name='HorariosViernes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_viernes', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_viernes', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_viernes', to='app_horarios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosSabados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_sabado', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_sabado', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_sabado', to='app_horarios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosMiercoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_miercoles', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_miercoles', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_miercoles', to='app_horarios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosMartes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_martes', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_martes', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_martes', to='app_horarios.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='HorariosJueves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_horario', models.CharField(default='', max_length=255)),
                ('hora_de_inicio_del_turno', models.TimeField()),
                ('hora_de_fin_del_turno', models.TimeField()),
                ('id_de_oficina', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='oficina_a_la_que_le_pertenece_horario_jueves', to='app_horarios.oficina')),
                ('id_del_chofer', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_chofer_jueves', to='app_horarios.chofer')),
                ('id_del_estudiante', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_de_estudiante_jueves', to='app_horarios.estudiante')),
            ],
        ),
    ]
