# Generated by Django 4.1.4 on 2023-01-08 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0022_horarioslunes_fecha_y_hora_en_la_que_se_registro_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosmartes',
            name='fecha_y_hora_en_la_que_se_registro_turno',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
