# Generated by Django 4.1.4 on 2023-01-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0026_alter_horarioslunes_fecha_y_hora_en_la_que_se_registro_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosjueves',
            name='fecha_y_hora_en_la_que_se_registro_turno',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horariosmiercoles',
            name='fecha_y_hora_en_la_que_se_registro_turno',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horariossabados',
            name='fecha_y_hora_en_la_que_se_registro_turno',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='horariosviernes',
            name='fecha_y_hora_en_la_que_se_registro_turno',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
