# Generated by Django 4.1.4 on 2023-01-08 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0028_peticionparacambiarhorario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peticionparacambiarhorario',
            old_name='nombre_y_fecha_y_hora_del_horario_que_deseas_modificar',
            new_name='nombre_del_chofer_y_fecha_y_hora_del_horario_que_deseas_modificar',
        ),
        migrations.AddField(
            model_name='peticionparacambiarhorario',
            name='id_del_chofer_del_horario_a_modificar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chofer_horario_a_modificar', to='app_horarios.chofer'),
        ),
    ]
