# Generated by Django 4.1.4 on 2023-01-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0030_semanadelhorario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemanaDelHorario',
            new_name='Semana',
        ),
    ]
