# Generated by Django 4.1.4 on 2023-01-09 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0031_rename_semanadelhorario_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosjueves',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_jueves', to='app_horarios.semana'),
        ),
        migrations.AddField(
            model_name='horarioslunes',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_lunes', to='app_horarios.semana'),
        ),
        migrations.AddField(
            model_name='horariosmartes',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_martes', to='app_horarios.semana'),
        ),
        migrations.AddField(
            model_name='horariosmiercoles',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_miercoles', to='app_horarios.semana'),
        ),
        migrations.AddField(
            model_name='horariossabados',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_sabado', to='app_horarios.semana'),
        ),
        migrations.AddField(
            model_name='horariosviernes',
            name='semana_del_turno',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='semana_del_turno_del_viernes', to='app_horarios.semana'),
        ),
    ]
