# Generated by Django 4.1.4 on 2023-01-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0034_semana_fecha_del_domingo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horarioslunes',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
    ]
