# Generated by Django 4.1.4 on 2023-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0035_horarioslunes_usara_carro_automatico_o_sincronico'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariosdomingos',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horariosjueves',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horariosmartes',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horariosmiercoles',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horariossabados',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='horariosviernes',
            name='usara_carro_automatico_o_sincronico',
            field=models.CharField(choices=[('CARRO AUTOMATICO', 'CARRO AUTOMATICO'), ('CARRO SINCRONICO', 'CARRO SINCRONICO')], default='', max_length=20),
        ),
    ]
