# Generated by Django 4.1.4 on 2023-01-11 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0036_horariosdomingos_usara_carro_automatico_o_sincronico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaParaReportesSemanales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_la_semana', models.CharField(default='', max_length=255)),
                ('fecha_de_inicio_de_semana_a_evaluar', models.DateField(default=datetime.date.today)),
                ('fecha_final_de_semana_a_evaluar', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
