# Generated by Django 4.1.4 on 2023-01-11 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_horarios', '0037_semanaparareportessemanales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportesemanal',
            name='id_de_semana',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='id_semana_para_reporte_semanal', to='app_horarios.semanaparareportessemanales'),
        ),
    ]
